### ISSUE TITLE
[BUG] Hide Next button on edit screen

### ISSUE THREAD

**Issue by daveosborne** [gembarrett/soap#116]
**Describe the bug**
Button is not clickable, should be hidden when in edit mode.

**To Reproduce**
1. Go to any question page
2. Click on edit button
3. Scroll down to bottom
4. See button

**Expected behavior**
Button should be hidden in edit mode.

**Comment by gembarrett** [comment]
This is intentional, the button is disabled rather than being hid. I don't know if hiding it, like the Preview button, would make much difference.
