### ISSUE TITLE
[BUG] Editable buttons difficult to select text

### ISSUE THREAD

**Issue by daveosborne** [gembarrett/soap#124]
**Describe the bug**
Editable buttons can be edited by selecting text in the box, but a single click toggles the selection, and so if the box is empty, adding text back can be difficult and worse on mobile.

**To Reproduce**
1. Go to a question with an editable button
2. Click on button
3. Delete all text
4. Click away from button
5. Try to add text back

**Expected behavior**
A double click should put the button into edit mode, focus loss should save text

**Comment by gembarrett** [comment]
Safari and Android both fine now
