### ISSUE TITLE
Field validity check broken by backspace

### ISSUE THREAD

**Issue by daveosborne** [gembarrett/soap#82]
**Describe the bug**
On any text field, pressing backspace causes the form to be invalid, and the next button is disabled until text is typed again.

**To Reproduce**
1. Go to first page with text input
2. Start typing
3. Press backspace
4. See button grey out and not be clickable

**Expected behavior**
Input field still has text, form should continue to be valid unless all text is erased

 - OS: Windows
 - Browser: Firefox, Chrome
 - Version: Latest

**Comment by gembarrett** [comment]
Need to look into event.key or onkeydown as potential fixes

**Comment by gembarrett** [comment]
@daveosborne can you test this on staging please?

**Comment by daveosborne** [comment]
LGTM
